import { useState, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
    MessageSquareText, Brain, ListChecks, Map, Settings, Sparkles,
    ChevronLeft, ChevronRight, BookOpen, Search, Zap, Loader2, Download, RefreshCw, ArrowRightCircle, Code, Lightbulb
} from "lucide-react";
import { useLearning } from "../context/LearningContext";
import { initializeGemini, generateRoadmap, generatePathfinder } from "../lib/gemini";
import TutorWindow from "../components/AiCompanion/TutorWindow";
import QuizWindow from "../components/AiCompanion/QuizWindow";

// Inline LearningRoadmap Component for Stability
function LearningRoadmap({ context, onSetKey, userProfile }) {
    const [loading, setLoading] = useState(true);
    const [roadmap, setRoadmap] = useState([]);
    const [error, setError] = useState(null);
    const [completedSteps, setCompletedSteps] = useState({});

    useEffect(() => {
        if (!context) return;
        const loadRoadmap = async () => {
            setLoading(true);
            setError(null);
            try {
                const data = await generateRoadmap(context, userProfile);
                setRoadmap(data.steps || data);
            } catch (err) {
                console.error(err);
                setError(err.message);
            } finally {
                setLoading(false);
            }
        };
        loadRoadmap();
    }, [context, userProfile]);

    const handleExportMD = () => {
        if (!roadmap.length) return;
        const title = context ? context.split('\n')[0].substring(0, 50) : "AI Action Plan";
        let content = `# AI Action Plan: ${title}\n\n`;
        content += `Generated on: ${new Date().toLocaleDateString()}\n\n`;
        content += `## Modules\n\n`;
        roadmap.forEach((item, index) => {
            const status = completedSteps[index] ? "[x]" : "[ ]";
            content += `${index + 1}. ${status} **${item.step}**\n`;
            if (item.details) content += `   - ${item.details}\n`;
            content += `\n`;
        });
        content += `---\n*Generated by LearnWise AI Expert*`;
        const blob = new Blob([content], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `roadmap_${new Date().getTime()}.md`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    if (loading) return (
        <div className="flex flex-col items-center justify-center py-12 text-zinc-500">
            <Loader2 className="w-10 h-10 animate-spin mb-4 text-blue-500" />
            <p>Drafting your action plan...</p>
        </div>
    );

    if (error || !roadmap.length) return (
        <div className="text-center py-8">
            <p className="text-red-500 mb-6 font-mono text-sm max-w-md mx-auto">{error || "No data received"}</p>
            <button onClick={onSetKey} className="flex items-center gap-2 mx-auto px-4 py-2 bg-zinc-900 text-yellow-500/80 border border-yellow-500/20 hover:text-yellow-400 transition-all font-mono text-xs uppercase tracking-tighter">
                <Settings className="w-4 h-4" /> [SET_CUSTOM_KEY]
            </button>
        </div>
    );

    return (
        <div className="max-w-xl mx-auto font-mono">
            <div className="mb-6 flex items-center justify-between px-1">
                <p className="text-[10px] text-zinc-500 uppercase tracking-widest">
                    PROGRESS_ANALYSIS: {Object.values(completedSteps).filter(Boolean).length}/{roadmap.length} MODULES_VERIFIED
                </p>
                <button onClick={handleExportMD} className="flex items-center gap-2 text-[10px] text-zinc-500 hover:text-white transition-colors border border-zinc-800 hover:border-zinc-700 px-2 py-1 bg-black uppercase tracking-tighter" title="DOWNLOAD AS MARKDOWN">
                    <Download className="w-3 h-3" /> [EXPORT_MD]
                </button>
            </div>
            <div className="space-y-3">
                {roadmap.map((item, index) => (
                    <div key={index} onClick={() => setCompletedSteps(p => ({ ...p, [index]: !p[index] }))} className={`group p-5 border transition-all flex items-start gap-5 cursor-pointer select-none ${completedSteps[index] ? "bg-black border-white/5 opacity-40" : "bg-black border-white/10 hover:border-blue-500/50"}`}>
                        <div className={`mt-1 transition-colors ${completedSteps[index] ? "text-green-500" : "text-zinc-700 group-hover:text-blue-500"}`}>
                            <div className={`w-5 h-5 border flex items-center justify-center ${completedSteps[index] ? "border-green-500 text-[10px] font-bold" : "border-zinc-700"}`}>
                                {completedSteps[index] ? "X" : ""}
                            </div>
                        </div>
                        <div>
                            <h4 className={`font-bold text-sm mb-2 tracking-wide ${completedSteps[index] ? "line-through text-zinc-600" : "text-white"}`}>
                                MODULE_{String(index + 1).padStart(2, '0')}: {item.step}
                            </h4>
                            {item.details && <p className="text-xs text-zinc-500 leading-relaxed italic">{item.details}</p>}
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}

// Inline LearningPathfinder Component for Stability
function LearningPathfinder({ context, onSetKey, userProfile }) {
    const [loading, setLoading] = useState(true);
    const [data, setData] = useState(null);
    const [error, setError] = useState(null);

    useEffect(() => {
        if (!context) return;
        const loadPathInfo = async () => {
            setLoading(true);
            setError(null);
            try {
                const result = await generatePathfinder(context, userProfile);
                setData(result);
            } catch (err) {
                console.error(err);
                setError(err.message);
            } finally {
                setLoading(false);
            }
        };
        loadPathInfo();
    }, [context, userProfile]);

    if (loading) return (
        <div className="flex flex-col items-center justify-center py-12 text-zinc-500">
            <Loader2 className="w-10 h-10 animate-spin mb-4 text-green-500" />
            <p>Charting your course...</p>
        </div>
    );

    if (error || !data) return (
        <div className="text-center py-8">
            <p className="text-red-500 mb-6 font-mono text-sm max-w-md mx-auto">{error || "No data received"}</p>
            <button onClick={onSetKey} className="flex items-center gap-2 mx-auto px-4 py-2 bg-zinc-900 text-yellow-500/80 border border-yellow-500/20 hover:text-yellow-400 transition-all font-mono text-xs uppercase tracking-tighter">
                <Settings className="w-4 h-4" /> [SET_CUSTOM_KEY]
            </button>
        </div>
    );

    return (
        <div className="max-w-xl mx-auto space-y-10 font-mono">
            <section className="bg-black border border-green-500/20 p-6 relative overflow-hidden group">
                <div className="absolute top-0 right-0 p-1 bg-green-500/10 text-green-500 text-[8px] font-bold tracking-tighter uppercase">REC_SYSTEM_V4</div>
                <div className="flex items-center gap-3 mb-4 text-green-500">
                    <ArrowRightCircle className="w-4 h-4" />
                    <span className="font-bold uppercase tracking-widest text-[10px]">Recommended_Next_Step</span>
                </div>
                <h3 className="text-2xl font-bold text-white mb-3 tracking-tight">{data.nextTopic?.title || "Advanced Concepts"}</h3>
                <p className="text-zinc-400 text-sm leading-relaxed italic border-l-2 border-green-500/40 pl-4">{data.nextTopic?.description}</p>
            </section>
            <section>
                <div className="flex items-center gap-3 mb-6 text-zinc-500 px-1 border-b border-white/5 pb-2">
                    <Lightbulb className="w-4 h-4" />
                    <h4 className="font-bold uppercase tracking-widest text-[10px]">Project_Ideation_Forge</h4>
                </div>
                <div className="grid gap-4">
                    {data.projects?.map((project, idx) => (
                        <div key={idx} className="bg-black p-6 border border-white/5 hover:border-purple-500/50 transition-all group relative">
                            <div className="flex justify-between items-start mb-4">
                                <h5 className="font-bold text-base text-white group-hover:text-purple-400 transition-colors uppercase tracking-wide">{project.title}</h5>
                                <span className={`px-2 py-0.5 text-[8px] font-bold uppercase tracking-tighter border ${project.difficulty === 'Beginner' ? 'border-green-500/50 text-green-500' : project.difficulty === 'Intermediate' ? 'border-yellow-500/50 text-yellow-500' : 'border-red-500/50 text-red-500'}`}>[{project.difficulty.substring(0, 3)}]</span>
                            </div>
                            <p className="text-xs text-zinc-500 mb-6 leading-relaxed">{project.description}</p>
                            <button className="text-[10px] font-bold text-zinc-600 group-hover:text-white flex items-center gap-2 transition-all uppercase tracking-widest"><Code className="w-3 h-3" /> [Start_Initiative]</button>
                        </div>
                    ))}
                </div>
            </section>
        </div>
    );
}

const MODES = [
    { id: "tutor", label: "AI Tutor", shortLabel: "Tutor", icon: MessageSquareText, color: "from-pink-500 to-rose-600", description: "Chat with your AI tutor" },
    { id: "quiz", label: "Test Knowledge", shortLabel: "Quiz", icon: Brain, color: "from-violet-500 to-purple-600", description: "Adaptive quizzes" },
    { id: "roadmap", label: "Learning Path", shortLabel: "Path", icon: ListChecks, color: "from-blue-500 to-cyan-600", description: "Step-by-step roadmap" },
    { id: "pathfinder", label: "Next Steps", shortLabel: "Next", icon: Map, color: "from-emerald-500 to-green-600", description: "What to learn next" },
];

export default function LearnWorkspace() {
    const {
        currentTopic, setCurrentTopic, apiKey, setApiKey, userProfile, setUserProfile,
        getDifficultyLevel, topicsExplored, addSessionEntry, masteryLevels
    } = useLearning();

    const [activeMode, setActiveMode] = useState("tutor");
    const [topicInput, setTopicInput] = useState(currentTopic || "");
    const [sidebarOpen, setSidebarOpen] = useState(true);
    const [showSettings, setShowSettings] = useState(false);
    const [localKey, setLocalKey] = useState(apiKey || "");
    const [localProfile, setLocalProfile] = useState(userProfile);

    const envKey = import.meta.env.VITE_GEMINI_API_KEY_PRIMARY || import.meta.env.VITE_GEMINI_API_KEY_FALLBACK;

    useEffect(() => {
        const key = apiKey || envKey;
        if (key) initializeGemini(key);
    }, [apiKey, envKey]);

    const context = currentTopic
        ? `Learning Topic: ${currentTopic}\nDifficulty Level: ${getDifficultyLevel(currentTopic)}\n\nThe user is studying "${currentTopic}". Adapt explanations to their ${getDifficultyLevel(currentTopic)} level. Focus on building understanding progressively.`
        : "General learning assistance. Ask the user what they'd like to learn.";

    const handleTopicSubmit = (e) => {
        e.preventDefault();
        if (topicInput.trim()) {
            setCurrentTopic(topicInput.trim());
            addSessionEntry({ type: "topic_change", topic: topicInput.trim() });
        }
    };

    const handleSaveSettings = () => {
        if (localKey.trim()) setApiKey(localKey.trim());
        setUserProfile(localProfile);
        setShowSettings(false);
    };

    const activeConfig = MODES.find((m) => m.id === activeMode);

    return (
        <div className="flex h-[calc(100vh-64px)] overflow-hidden bg-[var(--bg-primary)]">
            {/* Sidebar */}
            <AnimatePresence>
                {sidebarOpen && (
                    <motion.aside
                        initial={{ width: 0, opacity: 0 }}
                        animate={{ width: 280, opacity: 1 }}
                        exit={{ width: 0, opacity: 0 }}
                        transition={{ duration: 0.2 }}
                        className="bg-[var(--bg-secondary)] border-r border-white/5 flex flex-col overflow-hidden shrink-0"
                    >
                        <div className="p-4 border-b border-white/5">
                            <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-wider mb-3">AI Tools</h3>
                            <div className="space-y-1">
                                {MODES.map(({ id, label, icon: ModeIcon, color }) => (
                                    <button
                                        key={id}
                                        onClick={() => setActiveMode(id)}
                                        className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-all ${activeMode === id
                                            ? "bg-violet-600/15 text-violet-300 border border-violet-500/20"
                                            : "text-zinc-400 hover:text-white hover:bg-white/5"
                                            }`}
                                    >
                                        <div className={`w-7 h-7 rounded-md bg-gradient-to-br ${color} flex items-center justify-center`}>
                                            <ModeIcon className="w-3.5 h-3.5 text-white" />
                                        </div>
                                        {label}
                                    </button>
                                ))}
                            </div>
                        </div>

                        <div className="p-4 flex-1 overflow-y-auto">
                            <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-wider mb-3">Recent Topics</h3>
                            {topicsExplored.length > 0 ? (
                                <div className="space-y-1">
                                    {topicsExplored.slice(-10).reverse().map((t) => (
                                        <button
                                            key={t}
                                            onClick={() => { setCurrentTopic(t); setTopicInput(t); }}
                                            className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-sm transition-all group ${currentTopic === t
                                                ? "bg-white/5 text-white"
                                                : "text-zinc-500 hover:text-white hover:bg-white/5"
                                                }`}
                                        >
                                            <span className="truncate">{t}</span>
                                            {masteryLevels[t] !== undefined && (
                                                <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded ${masteryLevels[t] >= 70 ? "bg-green-500/15 text-green-400" : masteryLevels[t] >= 40 ? "bg-amber-500/15 text-amber-400" : "bg-red-500/15 text-red-400"}`}>
                                                    {masteryLevels[t]}%
                                                </span>
                                            )}
                                        </button>
                                    ))}
                                </div>
                            ) : (
                                <p className="text-xs text-zinc-600 italic">No topics explored yet</p>
                            )}
                        </div>

                        <div className="p-4 border-t border-white/5">
                            <button onClick={() => setShowSettings(true)} className="w-full flex items-center gap-2 px-3 py-2 rounded-lg text-xs text-zinc-500 hover:text-white hover:bg-white/5 transition-all">
                                <Settings className="w-4 h-4" /> Configure AI
                            </button>
                        </div>
                    </motion.aside>
                )}
            </AnimatePresence>

            <div className="flex-1 flex flex-col min-w-0">
                <div className="px-4 py-3 border-b border-white/5 flex items-center gap-3 bg-[var(--bg-secondary)]">
                    <button onClick={() => setSidebarOpen(!sidebarOpen)} className="p-2 text-zinc-500 hover:text-white hover:bg-white/5 rounded-lg transition-all">
                        {sidebarOpen ? <ChevronLeft className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
                    </button>
                    <form onSubmit={handleTopicSubmit} className="flex-1 relative">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600" />
                        <input type="text" value={topicInput} onChange={(e) => setTopicInput(e.target.value)} placeholder="What do you want to learn?..." className="w-full pl-10 pr-4 py-2.5 bg-black/40 border border-white/8 rounded-lg text-white placeholder:text-zinc-600 focus:outline-none focus:border-violet-500/40 text-sm" />
                    </form>
                    {currentTopic && (
                        <div className="hidden sm:flex items-center gap-2 px-3 py-1.5 bg-violet-600/10 border border-violet-500/20 rounded-lg">
                            <Zap className="w-3.5 h-3.5 text-violet-400" />
                            <span className="text-xs font-medium text-violet-300 capitalize">{getDifficultyLevel(currentTopic)}</span>
                        </div>
                    )}
                </div>

                <div className="px-6 py-4 flex items-center gap-3 border-b border-white/[0.03]">
                    <div className={`w-8 h-8 rounded-lg bg-gradient-to-br ${activeConfig.color} flex items-center justify-center`}>
                        {(() => { const ActiveIcon = activeConfig.icon; return <ActiveIcon className="w-4 h-4 text-white" />; })()}
                    </div>
                    <div>
                        <h2 className="font-bold text-white text-sm">{activeConfig.label}</h2>
                        <p className="text-[11px] text-zinc-500">{activeConfig.description} • {currentTopic || "General"}</p>
                    </div>
                </div>

                <div className="flex-1 overflow-y-auto p-6 scroll-smooth">
                    {activeMode === "tutor" && <TutorWindow context={context} onSetKey={() => setShowSettings(true)} userProfile={userProfile} />}
                    {activeMode === "quiz" && <QuizWindow context={context} onSetKey={() => setShowSettings(true)} userProfile={userProfile} />}
                    {activeMode === "roadmap" && <LearningRoadmap context={context} onSetKey={() => setShowSettings(true)} userProfile={userProfile} />}
                    {activeMode === "pathfinder" && <LearningPathfinder context={context} onSetKey={() => setShowSettings(true)} userProfile={userProfile} />}

                    <div className="mt-12 text-center opacity-40 hover:opacity-100 transition-opacity pb-12">
                        <p className="text-[10px] text-zinc-600 uppercase tracking-[0.2em] font-medium">
                            Developed by <a href="https://warriorwhocodes.com" target="_blank" rel="noopener noreferrer" className="text-violet-400 hover:text-violet-300">Ankush Singh Gandhi</a>
                        </p>
                        <p className="text-[8px] text-zinc-700 uppercase tracking-widest mt-1">
                            Powered by AntiGravity • Gemini 3.1 Pro • Gemini 3 Flash • Deployed on Google Cloud
                        </p>
                    </div>
                </div>
            </div>

            {showSettings && (
                <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
                    <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="glass rounded-2xl p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto">
                        <div className="flex items-center gap-3 mb-6">
                            <Settings className="w-5 h-5 text-violet-400" />
                            <h3 className="text-lg font-bold">AI Settings</h3>
                        </div>
                        <div className="space-y-4">
                            <div>
                                <label className="block text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-2">Gemini API Key</label>
                                <input type="password" value={localKey} onChange={(e) => setLocalKey(e.target.value)} placeholder="Paste Key..." className="w-full px-4 py-3 bg-black/50 border border-white/10 rounded-lg text-white placeholder:text-zinc-600 focus:outline-none focus:border-violet-500/50 font-mono text-sm" />
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-2">Role</label>
                                    <select value={localProfile.occupation} onChange={(e) => setLocalProfile({ ...localProfile, occupation: e.target.value })} className="w-full px-3 py-3 bg-black/50 border border-white/10 rounded-lg text-white text-sm focus:outline-none focus:border-violet-500/50">
                                        <option value="">Select...</option>
                                        <option value="student">Student</option>
                                        <option value="professional">Professional</option>
                                        <option value="self-learner">Self-Learner</option>
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-2">Goal</label>
                                    <select value={localProfile.goal} onChange={(e) => setLocalProfile({ ...localProfile, goal: e.target.value })} className="w-full px-3 py-3 bg-black/50 border border-white/10 rounded-lg text-white text-sm focus:outline-none focus:border-violet-500/50">
                                        <option value="">Select...</option>
                                        <option value="career">Career Growth</option>
                                        <option value="academic">Academic Study</option>
                                    </select>
                                </div>
                            </div>

                            <div>
                                <label className="block text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-2">Honest Self-Assessment</label>
                                <textarea value={localProfile.selfAssessment || ""} onChange={(e) => setLocalProfile({ ...localProfile, selfAssessment: e.target.value })} placeholder="e.g., 'I know React hooks but struggle with Redux. I'm a complete beginner at Node.js...'" className="w-full px-4 py-3 bg-black/50 border border-white/10 rounded-lg text-white placeholder:text-zinc-600 focus:outline-none focus:border-violet-500/50 font-mono text-sm min-h-[80px]" />
                            </div>

                            <div>
                                <label className="block text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-2">Paste Resume / Experience</label>
                                <textarea value={localProfile.resumeText || ""} onChange={(e) => setLocalProfile({ ...localProfile, resumeText: e.target.value })} placeholder="Paste your resume or list your professional experience here so the AI can tailor analogies to your background..." className="w-full px-4 py-3 bg-black/50 border border-white/10 rounded-lg text-white placeholder:text-zinc-600 focus:outline-none focus:border-violet-500/50 font-mono text-sm min-h-[100px]" />
                            </div>
                        </div>
                        <div className="flex gap-3 mt-6">
                            <button onClick={() => setShowSettings(false)} className="px-5 py-2.5 text-zinc-400 hover:text-white border border-white/10 rounded-lg transition-all">Cancel</button>
                            <button onClick={handleSaveSettings} className="flex-1 px-5 py-2.5 bg-gradient-to-r from-violet-600 to-indigo-600 text-white font-bold rounded-lg transition-all">Save Settings</button>
                        </div>
                    </motion.div>
                </div>
            )}
        </div>
    );
}
